default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] ? ENV['DATABASE_URL'] : `heroku config:get DATABASE_URL -a veggielocator-backend` %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
